# Unique identifier for the project
sonar.projectKey=N4ksu_Examify
sonar.projectName=Examify
sonar.projectVersion=1.0

# Path to the source code (relative to the root)
sonar.sources=.

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclude dependencies and tests from analysis to improve speed/accuracy
sonar.exclusions=**/node_modules/**, **/dist/**, **/bower_components/**
sonar.tests=src/**/*.test.js, src/**/*.spec.js
sonar.test.inclusions=**/*.spec.ts, **/*.spec.js, **/*.test.ts, **/*.test.js

# If it's a TypeScript project, you may need to point to the tsconfig
# sonar.typescript.tsconfigPath=tsconfig.json
